# Generated by Django 5.2.2 on 2025-07-15 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_budget_user_alter_tag_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('transactions', 'Recent Transactions'), ('notifications', 'Notifications'), ('balances', 'Account Balances'), ('budgets', 'Budget Overview')], max_length=32)),
                ('position', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['user'], name='core_dashbo_user_id_7e1f1e_idx'), models.Index(fields=['position'], name='core_dashbo_positio_633c3f_idx')],
                'unique_together': {('user', 'widget_type')},
            },
        ),
    ]
