# Generated by Django 5.2.2 on 2025-07-16 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dashboardbalancepreference'),
        ('plaid_link', '0007_remove_transaction_user_tag_transaction_tag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dashboardbalancepreference',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dashboardbalancepreference',
            name='accounts',
            field=models.ManyToManyField(related_name='dashboard_balance_preferences', to='plaid_link.account'),
        ),
        migrations.AlterField(
            model_name='dashboardbalancepreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='dashboardbalancepreference',
            name='account',
        ),
    ]
