# Generated by Django 5.2.2 on 2025-07-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_accountbalancesnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardwidget',
            name='widget_type',
            field=models.CharField(choices=[('transactions', 'Recent Transactions'), ('net worth', 'Net Worth'), ('balances', 'Account Balances'), ('budgets', 'Budget Overview'), ('balance change', 'Balance Change')], max_length=32),
        ),
    ]
