# Generated by Django 5.2.2 on 2025-07-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_dashboardwidget_widget_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardwidget',
            name='widget_type',
            field=models.CharField(choices=[('transactions', 'Recent Transactions'), ('net_worth', 'Net Worth'), ('balances', 'Account Balances'), ('budgets', 'Budget Overview'), ('balance_change', 'Balance Change'), ('top_categories', 'Top Spending Categories')], max_length=32),
        ),
    ]
