# Generated by Django 5.2.2 on 2025-06-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_link', '0002_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category_detailed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category_main',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
