# Generated by Django 5.2.2 on 2025-06-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_link', '0003_remove_transaction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
