# Generated by Django 5.2.2 on 2025-07-08 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_budget_categories_tag_budget_tags"),
        ("plaid_link", "0004_transaction_user_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="user_tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.tag",
            ),
        ),
    ]
