# Generated by Django 5.2.2 on 2025-07-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plaid_link", "0005_alter_transaction_user_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
